name: Run Walmart Pipeline

on:
  schedule:
    - cron: '33 9 * * *'  # Daily at 3 PM IST
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pymongo pandas rapidfuzz joblib

      - name: Run master script
        run: python PythonWalmartAutomate.py

      - name: Save model artifact
        uses: actions/upload-artifact@v4
        with:
          name: fraud_detection_model
          path: fraud_detection_model.joblib
