name: Walmart Fraud Detection Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pymongo

      - name: Check customer count and handle CSVs
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python <<EOF
          from pymongo import MongoClient
          import os

          uri = os.getenv("MONGO_URI")
          client = MongoClient(uri)
          db = client["WalmartDatabase"]
          customers = db["customers"]
          count = customers.count_documents({})

          print(f"Customer count: {count}")

          if count == 0:
              print("No customers found. Emptying CSV files (except fraudsummary.csv)...")
              for filename in ["fraudsummaryall.csv", "new_customers_predictions.csv", "finalfraudsummary_export.csv"]:
                  with open(filename, "w") as f:
                      f.write("")
                      
      - name: Run master script
        if: success()
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python PythonWalmartAutomate.py

      - name: Commit and push updated CSVs only
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add fraudsummaryall.csv new_customers_predictions.csv finalfraudsummary_export.csv || true
          git status
          git commit -m "Update fraud CSVs based on customer input [skip ci]" || echo "No changes to commit"
          git push
