name: Walmart Fraud Detection Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run master script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python PythonWalmartAutomate.py

      # Commit and push both output CSVs
      - name: Commit and push updated CSVs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add finalfraudsummary_export.csv fraudsummaryall.csv
          git status
          git commit -m "Update fraud summary CSVs [skip ci]" || echo "No changes to commit"
          git push
