name: Walmart Fraud Detection Pipeline

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 min UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keep GitHub token for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run master script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python PythonWalmartAutomate.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fraud_detection_artifacts
          path: |
            fraud_detection_model.joblib
            fraudsummary.csv

      - name: Force add, commit, and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f fraud_detection_model.joblib fraudsummary.csv
          git commit -m "Auto update: model + fraudsummary.csv [run ${{ github.run_id }}]" || echo "No changes to commit"
          git push
