name: Walmart Fraud Detection Pipeline

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 min UTC
  workflow_dispatch:

permissions:
  contents: write  # Needed to push commits

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keep token to allow push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run master script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python PythonWalmartAutomate.py

      - name: Commit updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fraudsummary.csv fraud_detection_model.joblib
          git commit -m "Auto update fraudsummary.csv + model [Run ID: ${{ github.run_id }}]" || echo "No changes to commit"
          git push origin main
