name: Walmart Fraud Detection Pipeline

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Needed for committing and pushing changes

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keeps token for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run master script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python PythonWalmartAutomate.py

      - name: Commit model + CSV to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Force add files (even if ignored in .gitignore)
          git add -f fraud_detection_model.joblib fraudsummary.csv
          
          # Commit if there are changes
          git commit -m "Auto update: fraud_detection_model + fraudsummary.csv [run ${{ github.run_id }}]" || echo "No changes to commit"
          
          # Push to the current branch
          git push

