# GitHub Actions Workflow for Walmart Fraud Detection Automation

name: Walmart Fraud Detection Pipeline

# Allows manual triggering from the GitHub UI
on:
  workflow_dispatch:

# Required permissions to write updated files back to the repo
permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # Use latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Retain Git credentials for later pushes

      # Step 2: Set up the required Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the main fraud detection automation script
      - name: Run master script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Use secret for secure DB access
        run: |
          python PythonWalmartAutomate.py

      # Step 5: Commit updated fraudsummary.csv file if it exists
      - name: Commit fraudsummary.csv if it exists
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f fraudsummary.csv ]; then
            git add fraudsummary.csv
            git commit -m "Update fraudsummary.csv [Run ID: ${{ github.run_id }}]" || echo "No changes to commit for CSV"
            git push origin main
          else
            echo "fraudsummary.csv not found. Skipping commit."

      # Step 6: Commit the trained model file if it exists
      - name: Commit fraud_detection_model.joblib if it exists
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f fraud_detection_model.joblib ]; then
            git add fraud_detection_model.joblib
            git commit -m "Update model file [Run ID: ${{ github.run_id }}]" || echo "No changes to commit for model"
            git push origin main
          else
            echo "fraud_detection_model.joblib not found. Skipping commit."

      # Step 7: Delete and commit model file if it was removed (i.e., zero customers case)
      - name: Commit deletion if model was removed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ ! -f fraud_detection_model.joblib ]; then
            git rm -f fraud_detection_model.joblib || echo "Already removed"
            git commit -m "Remove model due to 0 customers [Run ID: ${{ github.run_id }}]" || echo "No changes to commit"
            git push origin main
          else
            echo "Model still exists, no deletion."
